### ISSUE TITLE
[Request] Publish extension to Open VSX

### ISSUE THREAD

**Issue by kdkasad** [kitgore/BongoCat#1]
It would be great if you could make this extension available on [Open VSX](https://open-vsx.org/) in addition to Microsoft's extension marketplace. This would allow forks of VSCode (e.g. VSCodium) to download the extension.

**Comment by kitgore** [comment]
Thanks for the suggestion! Just published it [here](https://open-vsx.org/extension/pixl-garden/BongoCat) :)
